pipeline:
  install_node:
    image: node:10-alpine
    commands:
      - npm install
      - npm run build
  build-image:
    image: hub.gyg.io/drone-plugins/gyg-registry
    privileged: true
    context: .
    dockerfile: ./Dockerfile
    repo: hub.gyg.io/orphan/webpack-dev-example
    tags:
      - ${DRONE_BUILD_NUMBER}.${DRONE_COMMIT_SHA:0:7}
    when:
      event: push
  register-dss:
    image: hub.gyg.io/drone-plugins/dss
    privileged: true
    repo: hub.gyg.io/orphan/webpack-dev-example
    tags:
      - ${DRONE_BUILD_NUMBER}.${DRONE_COMMIT_SHA:0:7}
    when:
      event: push
