# This file was generated by gygdev. Do not manually modify it
FROM node:10-alpine

RUN apk add dumb-init

RUN mkdir /app

COPY . /app/

WORKDIR /app
RUN npm install

RUN npm run build

EXPOSE 3000

CMD ["dumb-init", "node", "index.js"]
